# Име на приложението
spring.application.name=ticket-system

# Връзка с MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/cinema_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=sigma

# JPA / Hibernate - автоматично създава/обновява таблиците
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Сървърът ще слуша на порт 8080
server.port=8080